version: '3.8'
services:
  webapi:
    build: .
    ports:
      - "8080:80"
    environment:
      - ConnectionStrings__sqlConnection=Server=sqlserver;initial Catalog=MovieApiDb;User Id=sa;Password=YourSecurePassword;TrustServerCertificate=true;
    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "YourSecurePassword"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
