openapi: 3.0.1
info:
  title: WebAPI
  version: '1.0'
paths:
  /api/Actors:
    get:
      tags:
        - Actors
      responses:
        '200':
          description: Success
    post:
      tags:
        - Actors
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateActorDto'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateActorDto'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateActorDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateActorDto'
      responses:
        '200':
          description: Success
    put:
      tags:
        - Actors
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/UpdateActorDto'
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateActorDto'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateActorDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateActorDto'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Actors
      parameters:
        - name: id
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  '/api/Actors/{id}':
    get:
      tags:
        - Actors
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  '/api/Actors/GetActorWithMovies/{id}':
    get:
      tags:
        - Actors
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/Genres:
    get:
      tags:
        - Genres
      responses:
        '200':
          description: Success
    post:
      tags:
        - Genres
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateGenreDto'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateGenreDto'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateGenreDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateGenreDto'
      responses:
        '200':
          description: Success
    put:
      tags:
        - Genres
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/UpdateGenreDto'
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateGenreDto'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateGenreDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateGenreDto'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Genres
      parameters:
        - name: id
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  '/api/Genres/{id}':
    get:
      tags:
        - Genres
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  '/api/Genres/GetGenreByIdWithMovies/{id}':
    get:
      tags:
        - Genres
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/Movies:
    get:
      tags:
        - Movies
      responses:
        '200':
          description: Success
    post:
      tags:
        - Movies
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateMovieDto'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMovieDto'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateMovieDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateMovieDto'
      responses:
        '200':
          description: Success
    put:
      tags:
        - Movies
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/UpdateMovieDto'
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateMovieDto'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateMovieDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateMovieDto'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Movies
      parameters:
        - name: id
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  '/api/Movies/{id}':
    get:
      tags:
        - Movies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  '/api/Movies/GetMovieByIdWithAll/{id}':
    get:
      tags:
        - Movies
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  /api/Reviews:
    get:
      tags:
        - Reviews
      responses:
        '200':
          description: Success
    post:
      tags:
        - Reviews
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/CreateReviewDto'
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReviewDto'
          text/json:
            schema:
              $ref: '#/components/schemas/CreateReviewDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/CreateReviewDto'
      responses:
        '200':
          description: Success
    put:
      tags:
        - Reviews
      requestBody:
        content:
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/UpdateReviewDto'
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateReviewDto'
          text/json:
            schema:
              $ref: '#/components/schemas/UpdateReviewDto'
          application/*+json:
            schema:
              $ref: '#/components/schemas/UpdateReviewDto'
      responses:
        '200':
          description: Success
    delete:
      tags:
        - Reviews
      parameters:
        - name: id
          in: query
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  '/api/Reviews/{id}':
    get:
      tags:
        - Reviews
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
  '/api/Reviews/GetReviewsByMovieId/{id}':
    get:
      tags:
        - Reviews
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: Success
components:
  schemas:
    CreateActorDto:
      type: object
      properties:
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        birthDate:
          type: string
          format: date-time
        description:
          type: string
          nullable: true
      additionalProperties: false
    CreateGenreDto:
      type: object
      properties:
        name:
          type: string
          nullable: true
      additionalProperties: false
    CreateMovieDto:
      type: object
      properties:
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        actorIds:
          type: array
          items:
            type: integer
            format: int32
          nullable: true
        genreIds:
          type: array
          items:
            type: integer
            format: int32
          nullable: true
      additionalProperties: false
    CreateReviewDto:
      type: object
      properties:
        rating:
          type: integer
          format: int32
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        author:
          type: string
          nullable: true
        movieId:
          type: integer
          format: int32
      additionalProperties: false
    UpdateActorDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        firstName:
          type: string
          nullable: true
        lastName:
          type: string
          nullable: true
        birthDate:
          type: string
          format: date-time
        description:
          type: string
          nullable: true
      additionalProperties: false
    UpdateGenreDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
      additionalProperties: false
    UpdateMovieDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        name:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        genreId:
          type: integer
          format: int32
      additionalProperties: false
    UpdateReviewDto:
      type: object
      properties:
        id:
          type: integer
          format: int32
        rating:
          type: integer
          format: int32
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
      additionalProperties: false
